name: Update Static Page with Run Time

on:
  workflow_dispatch:  # Manual run
  schedule:
    - cron: '0 * * * *'  # Optional: every hour

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Append date and time to HTML file
        run: |
          TIMESTAMP=$(date)
          sed -i "/<ul id=\"log\">/a \ \ \ \ <li>$TIMESTAMP</li>" index.html

      - name: Commit and push changes
        env:
          TOKEN: ${{ secrets.PAT_X }}
        run: |
          git add index.html
          git commit -m "Update log with timestamp: $(date)" || echo "No changes to commit"
          
          # Use the token explicitly for pushing
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
          git push origin HEAD:main
